In [1]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
y_hat = np.linspace(-1, 1, 20)
y = np.linspace(0, 1, 20)

In [3]:
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [4]:
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [5]:
y_hat = np.linspace(-1, 1, 20)
y = np.linspace(0, 1, 20)

def mse(x,y,n):
    return np.sum((x-y)**2)/n

def mae(x,y,n):
    return np.sum(abs(x-y))/n

def msle(x,y,n):
    return np.sum((np.log(x+1) - np.log(y+1))**2)/n

def mape(x,y,n):
    return np.sum(abs((x-y)/y))/n

def shape(x):
    return x.shape

def dimension(x):
    return x.ndim

mseL = mse(y_hat,y,20)
maeL = mae(y_hat,y,20)
msleL = msle(y_hat,y,20)
mapeL = mape(y_hat,y,20)

y_hatShape = shape(y_hat)
y_Shape = shape(y)

y_hatDimension = dimension(y_hat)
y_Dimension = dimension(y)

print("These are the answers for Assignment 1 Part 1:")
print("This is the Mean Squared Error: ", mseL)
print("This is the Mean Absolute Error: ", maeL)
print("This is the Mean Squared Logarithmic Error: ", msleL)
print("This is the Mean Absolute Percentage Error: ", mapeL)
print ("This is the shape and dimension of Y hat: ", y_hatShape, y_hatDimension)
print ("This is the shape and dimension of Y: ", y_Shape, y_Dimension)

These are the answers for Assignment 1 Part 1:
This is the Mean Squared Error:  0.3421052631578948
This is the Mean Absolute Error:  0.4999999999999999
This is the Mean Squared Logarithmic Error:  inf
This is the Mean Absolute Percentage Error:  inf
This is the shape and dimension of Y hat:  (20,) 1
This is the shape and dimension of Y:  (20,) 1


C:\Users\rk020\AppData\Local\Temp\ipykernel_17668\1527436853.py:11: RuntimeWarning: divide by zero encountered in log
  return np.sum((np.log(x+1) - np.log(y+1))**2)/n
C:\Users\rk020\AppData\Local\Temp\ipykernel_17668\1527436853.py:14: RuntimeWarning: divide by zero encountered in true_divide
  return np.sum(abs((x-y)/y))/n


In [6]:
M = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
N = M.reshape(4,4)
S = N[1,:]
min = np.min(N, axis = 0)
locate = N.argmin(axis=0)
mean = N.mean()
V = np.array([1,1,1,1])
Dot = np.dot(N,V)

print ("This is the Array M \n", M)
print ("This is the 4 by 4 Array N \n", N)
print ("This is the second row of Array N \n", S)
print ("This is the minimum values of Column of Array N \n", min)
print("This are the locations of the minimun values of Column of Array N \n", locate)
print("This is the mean of the Array N \n", mean)
print("This is the  vector V with 4 elements \n", V)
print("This is the dot product of N and V \n", Dot)

This is the Array M 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
This is the 4 by 4 Array N 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
This is the second row of Array N 
 [5 6 7 8]
This is the minimum values of Column of Array N 
 [1 2 3 4]
This are the locations of the minimun values of Column of Array N 
 [0 0 0 0]
This is the mean of the Array N 
 8.5
This is the  vector V with 4 elements 
 [1 1 1 1]
This is the dot product of N and V 
 [10 26 42 58]
